version: "3.8"
services:
  agixt:
    image: localagi/agixt:main
    entrypoint: [ "streamlit", "run", "Main.py" ]
    init: true
    ports:
      - "8501:8501"
    volumes:
      - ./data/agents:/agixt/agents:rw
      - ./data/workspace:/agixt/WORKSPACE:rw
      - ./models:/model:rw
    profiles: ["all","streamlit"]
