version: "3.8"
services:
  agixt:
    image: localagi/agixt:build-localagi
    entrypoint: [ "poetry", "run", "streamlit", "run", "Main.py" ]
    init: true
    ports:
      - "8501:8501"
    volumes:
      - ./data/agents:/agixt/agents:rw
      - ./data/workspace:/agixt/WORKSPACE:rw
      - ./cache/torch:/root/.cache/torch
      - ./models:/model:rw
