version: "3.8"
services:
  frontend:
    image: ghcr.io/jamesonrgrieve/agent-llm-frontend:main
    init: true
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://backend:7437}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    profiles: ["all","frontend"]
    
  backend:
    image: localagi/agixt:main
    init: true
    ports:
      - "7437:7437"
    volumes:
      - ./data/agents:/app/agents:rw
      - ./data/workspace:/app/WORKSPACE:rw
      - ./models:/model:rw
    profiles: ["all","backend", "frontend"]

  backend-streamlit:
    image: localagi/agixt:main
    entrypoint: [ "streamlit", "run", "Main.py" ]
    init: true
    ports:
      - "8501:8501"
    volumes:
      - ./data/agents:/app/agents:rw
      - ./data/workspace:/app/WORKSPACE:rw
      - ./models:/model:rw
    profiles: ["all","streamlit"]
