name: Publish Docker images

permissions:
  packages: write
  contents: read
  
on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:
  
jobs:

  build-agixt:
    uses: localagi/ai-dedicated-workflows/.github/workflows/operation-docker-build-publish.yml@main
    with:
      registry-repo-name: agixt
      context-repository: Josh-XT/AGiXT
      context-repository-ref: ${{ github.ref }}
      registry-readme: README.docker.md
      tags: |
        type=schedule
        type=ref,event=branch
        type=semver,pattern={{version}}
#      platforms: linux/amd64,linux/arm64/v8
      cache-from: ${{ null }}
    secrets: inherit
