name: Publish and test Docker images

permissions:
  packages: write
  contents: read
  
on:
  pull_request:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:
  
jobs:

  build-agixt:
    uses: localagi/AI-pipeline/.github/workflows/operation-docker-build-publish.yml@v3
    with:
      registry-repo-name: AGiXT
      context-repository: localagi/AGiXT
      context-repository-ref: ${{ github.ref }}
      tags: |
        type=schedule
        type=ref,event=branch
        type=semver,pattern={{version}}
      #platforms: linux/amd64,linux/arm64/v8
    secrets: inherit
    
  test-agixt:
    uses: localagi/AI-pipeline/.github/workflows/operation-test-with-jupyter.yml@main
    with:
      image: ${{ needs.build-agixt.outputs.primary-image }}
      port: "7437" 
      additional-python-dependencies: requests
    secrets:
      api-key: ${{ secrets.OPENAI_API_KEY }}
    needs: build-agixt
