name: Test junyper notebooks

on:
  #  push:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
#    container: python:3.10-slim-buster

    services:
      Agent-LLM:
        image: localagi/agixt:main
        ports:
          - 7437:7437

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install jupyter and deps
        run: pip3 install jupyter nbconvert[webpdf]


      - name: Execute notebook
        run: python3 -m nbconvert --execute --to webpdf --allow-chromium-download agixt/API-Tests.ipynb 
        
      - name: Upload result
        run: upload artefact
